// Code generated by goctl. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	userConversationFieldNames          = builder.RawFieldNames(&UserConversation{})
	userConversationRows                = strings.Join(userConversationFieldNames, ",")
	userConversationRowsExpectAutoSet   = strings.Join(stringx.Remove(userConversationFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	userConversationRowsWithPlaceHolder = strings.Join(stringx.Remove(userConversationFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	userConversationModel interface {
		Insert(ctx context.Context, data *UserConversation) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*UserConversation, error)
		Update(ctx context.Context, data *UserConversation) error
		Delete(ctx context.Context, id int64) error
	}

	defaultUserConversationModel struct {
		conn  sqlx.SqlConn
		table string
	}

	UserConversation struct {
		Id             int64     `db:"id"`
		UserId         int64     `db:"user_id"`         // 用户id
		ConversationId int64     `db:"conversation_id"` // 会话记录id
		FirstTime      time.Time `db:"first_time"`
		LastTime       time.Time `db:"last_time"`
	}
)

func newUserConversationModel(conn sqlx.SqlConn) *defaultUserConversationModel {
	return &defaultUserConversationModel{
		conn:  conn,
		table: "`user_conversation`",
	}
}

func (m *defaultUserConversationModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultUserConversationModel) FindOne(ctx context.Context, id int64) (*UserConversation, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userConversationRows, m.table)
	var resp UserConversation
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserConversationModel) Insert(ctx context.Context, data *UserConversation) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, userConversationRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserId, data.ConversationId, data.FirstTime, data.LastTime)
	return ret, err
}

func (m *defaultUserConversationModel) Update(ctx context.Context, data *UserConversation) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, userConversationRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.UserId, data.ConversationId, data.FirstTime, data.LastTime, data.Id)
	return err
}

func (m *defaultUserConversationModel) tableName() string {
	return m.table
}
